language: ruby
script: rake spec
before_script:
  - psql -c 'create database fast_seeder_test;' -U postgres
  - mysql -e 'create database fast_seeder_test;'
rvm:
  - 2.0.0
  - 2.1.2
env:
   - ADAPTER=postgresql
   - ADAPTER=mysql
   - ADAPTER=mysql2
   - ADAPTER=sqlite3
branches:
  only:
    - master
